config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  resources :customer_records
  root 'top#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer_record.rb
class CustomerRecord < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customer_records_controller.rb
class CustomerRecordsController < ApplicationController
  before_action :set_customer_record, only: %i[ show edit update destroy ]

  # GET /customer_records or /customer_records.json
  def index
    @customer_records = CustomerRecord.all
  end

  # GET /customer_records/1 or /customer_records/1.json
  def show
  end

  # GET /customer_records/new
  def new
    @customer_record = CustomerRecord.new
  end

  # GET /customer_records/1/edit
  def edit
  end

  # POST /customer_records or /customer_records.json
  def create
    @customer_record = CustomerRecord.new(customer_record_params)

    respond_to do |format|
      if @customer_record.save
        format.html { redirect_to customer_record_url(@customer_record), notice: "Customer record was successfully created." }
        format.json { render :show, status: :created, location: @customer_record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_records/1 or /customer_records/1.json
  def update
    respond_to do |format|
      if @customer_record.update(customer_record_params)
        format.html { redirect_to customer_record_url(@customer_record), notice: "Customer record was successfully updated." }
        format.json { render :show, status: :ok, location: @customer_record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_records/1 or /customer_records/1.json
  def destroy
    @customer_record.destroy

    respond_to do |format|
      format.html { redirect_to customer_records_url, notice: "Customer record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_record
      @customer_record = CustomerRecord.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_record_params
      params.require(:customer_record).permit(:date, :customer_name, :staff_name, :note)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_records_helper.rb
module CustomerRecordsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/customer_records/_form.html.erb
<%= form_with(model: customer_record) do |form| %>
  <% if customer_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer_record.errors.count, "error") %> prohibited this customer_record from being saved:</h2>

      <ul>
        <% customer_record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name %>
  </div>

  <div class="field">
    <%= form.label :staff_name %>
    <%= form.text_field :staff_name %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customer_records/edit.html.erb
<h1>Editing Customer Record</h1>

<%= render 'form', customer_record: @customer_record %>

<%= link_to 'Show', @customer_record %> |
<%= link_to 'Back', customer_records_path %>

app/views/customer_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customer Records</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Customer name</th>
      <th>Staff name</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_records.each do |customer_record| %>
      <tr>
        <td><%= customer_record.date %></td>
        <td><%= customer_record.customer_name %></td>
        <td><%= customer_record.staff_name %></td>
        <td><%= customer_record.note %></td>
        <td><%= link_to 'Show', customer_record %></td>
        <td><%= link_to 'Edit', edit_customer_record_path(customer_record) %></td>
        <td><%= link_to 'Destroy', customer_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer Record', new_customer_record_path %>

app/views/customer_records/new.html.erb
<h1>New Customer Record</h1>

<%= render 'form', customer_record: @customer_record %>

<%= link_to 'Back', customer_records_path %>

app/views/customer_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @customer_record.date %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @customer_record.customer_name %>
</p>

<p>
  <strong>Staff name:</strong>
  <%= @customer_record.staff_name %>
</p>

<p>
  <strong>Note:</strong>
  <%= @customer_record.note %>
</p>

<%= link_to 'Edit', edit_customer_record_path(@customer_record) %> |
<%= link_to 'Back', customer_records_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<h1>Top#index</h1>
<p>Find me in app/views/top/index.html.erb</p>